### ISSUE TITLE
tinymce fails to load

### ISSUE THREAD

**Issue by propertunist** [iionly/extended_tinymce#5] opened 2017-04-22 17:50 UTC
i have been using extended tinymce on my site for years and all through that time there have been occasions where it fails to load or it loads but there is an error and the text area is white and unusable - instead of being coloured as it would normally be in my site's theme.
i just found that now this problem is 100% reproducible in certain circumstances, so we may be able to fix it.
i am using tinymce for comments in the popups that open in tidypics_plus when the user clicks an image thumbnail in the album view. the first time the popup is fired, it all works correctly. the second time it is fired on the same page, the error with the unusable text input field occurs and the third time (and all further times) the whole player fails to load.

here's what i see in the JS console for the 1st error, unfortunately i have no idea presently what the issue is:
```
TypeError: e is undefined
Stack trace:
r@https://www.ureka.org//mod/extended_tinymce/vendor/tinymce/js/tinymce/tinymce.min.js:13:17430
a@https://www.ureka.org//mod/extended_tinymce/vendor/tinymce/js/tinymce/tinymce.min.js:13:17647
i/</<@https://www.ureka.org//mod/extended_tinymce/vendor/tinymce/js/tinymce/tinymce.min.js:13:18353
i@https://www.ureka.org//mod/extended_tinymce/vendor/tinymce/js/tinymce/tinymce.min.js:8:21943
fire@https://www.ureka.org//mod/extended_tinymce/vendor/tinymce/js/tinymce/tinymce.min.js:8:23840
this.nodeChanged@https://www.ureka.org//mod/extended_tinymce/vendor/tinymce/js/tinymce/tinymce.min.js:4:22850
nodeChanged@https://www.ureka.org//mod/extended_tinymce/vendor/tinymce/js/tinymce/tinymce.min.js:12:2022
@https://www.ureka.org//mod/extended_tinymce/vendor/tinymce/js/tinymce/tinymce.min.js:7:22069
i@https://www.ureka.org//mod/extended_tinymce/vendor/tinymce/js/tinymce/tinymce.min.js:8:21943
fire@https://www.ureka.org//mod/extended_tinymce/vendor/tinymce/js/tinymce/tinymce.min.js:8:23840
add@https://www.ureka.org//mod/extended_tinymce/vendor/tinymce/js/tinymce/tinymce.min.js:7:22720
@https://www.ureka.org//mod/extended_tinymce/vendor/tinymce/js/tinymce/tinymce.min.js:7:20882
i@https://www.ureka.org//mod/extended_tinymce/vendor/tinymce/js/tinymce/tinymce.min.js:8:21943
fire@https://www.ureka.org//mod/extended_tinymce/vendor/tinymce/js/tinymce/tinymce.min.js:8:23840
initContentBody@https://www.ureka.org//mod/extended_tinymce/vendor/tinymce/js/tinymce/tinymce.min.js:11:31912
init@https://www.ureka.org//mod/extended_tinymce/vendor/tinymce/js/tinymce/tinymce.min.js:11:28850
t/<@https://www.ureka.org//mod/extended_tinymce/vendor/tinymce/js/tinymce/tinymce.min.js:11:23870
v/<@https://www.ureka.org//mod/extended_tinymce/vendor/tinymce/js/tinymce/tinymce.min.js:4:11637
n@https://www.ureka.org//mod/extended_tinymce/vendor/tinymce/js/tinymce/tinymce.min.js:3:1531
v@https://www.ureka.org//mod/extended_tinymce/vendor/tinymce/js/tinymce/tinymce.min.js:4:11594
n/this.loadScripts@https://www.ureka.org//mod/extended_tinymce/vendor/tinymce/js/tinymce/tinymce.min.js:4:11344
n/this.loadQueue@https://www.ureka.org//mod/extended_tinymce/vendor/tinymce/js/tinymce/tinymce.min.js:4:11154
t@https://www.ureka.org//mod/extended_tinymce/vendor/tinymce/js/tinymce/tinymce.min.js:11:23836
render@https://www.ureka.org//mod/extended_tinymce/vendor/tinymce/js/tinymce/tinymce.min.js:11:25200
s/<@https://www.ureka.org/mod/extended_tinymce/vendor/tinymce/js/tinymce/jquery.tinymce.min.js:1:2230
each@https://cdn.jsdelivr.net/jquery/2.2.1/jquery.min.js:2:2771
s@https://www.ureka.org/mod/extended_tinymce/vendor/tinymce/js/tinymce/jquery.tinymce.min.js:1:2207
e.fn.tinymce@https://www.ureka.org/mod/extended_tinymce/vendor/tinymce/js/tinymce/jquery.tinymce.min.js:1:2421
@https://cdn.jsdelivr.net/jquery/2.2.1/jquery.min.js line 2 > eval:4:3
execCb@https://cdn.jsdelivr.net/requirejs/2.1.22/require.min.js:30:206
check@https://cdn.jsdelivr.net/requirejs/2.1.22/require.min.js:18:420
enable@https://cdn.jsdelivr.net/requirejs/2.1.22/require.min.js:24:63
init@https://cdn.jsdelivr.net/requirejs/2.1.22/require.min.js:17:109
e/<@https://cdn.jsdelivr.net/requirejs/2.1.22/require.min.js:27:221
nrWrapper@https://www.ureka.org/photos/siteimagesall:4:11497
```

**Comment by iionly** [comment] 2017-04-23 13:34
Sorry. But it seems I can currently not reproduce the issue as Tidypics_plus might not be compatible with the latest Tidypics release 2.3.3. Or the Elgg Slider plugin might not be compatible with Elgg 2.x. I can't say what exactly is not working / compatible on the latest Elgg 2.3 but the resulting issue is that the image doesn't open in a popup at all. Instead I just get an invalid request error.

I have no Elgg test installation with Elgg 2.0 - 2.2 anymore but only an Elgg 2.3 test installation. And I won't have any time trying to fix possible errors in other plugins but mine to be able to find out if there might be a bug in one of my own plugins. If there are working releases for Elgg 2.3 of all plugins necessary available I can give it another try but not before.

If there's an issue with Extended Tinymce it could be due to tinymce requires a slightly different init procedure within ajax context (e.g. used on the activity page). Maybe this causes also a problem with the Tidypics_plus popups. You could try setting the "ajax" context explicitely in your code. Maybe it helps. Other than that I can only imagine that there might be some dependency issue with loading of AMD modules / a race condition on loading possible with galliComments (if this plugin is mandatory to be used when using the image popups).

**Comment by propertunist** [comment] 2017-04-25 15:19
ok, i didn't realise i hadn't udloaded a 2.3 version of tidypics plus - i have uploaded it now. 
i just tried setting the ajax context and that appears to have fixed the issue. thanks for the tip!

**Comment by propertunist** [comment] 2017-05-03 20:03
i spoke too soon.. this issue is still occurring, i'm not sure why it appeared to be fixed previously.

**Comment by iionly** [comment] 2017-05-03 21:11
galliComments loads its JS code by just extending js/elgg whereas Extended Tinymce uses AMD modules. The AMD modules are loaded async and therefore the galliComments JS code takes action sometimes before the tinymce editor is fully loaded. In this case it fails. galliComments also still uses elgg.provide() which is not recommened anymore. I think it works with CKeditor only because the galliComments JS code doesn't explicitely call any ckeditor API functions or maybe the CKeditor stuff is required at an earlier stage already during booting of the Elgg engine.

I think it's necessary to rewrite the JS code of galliComments into an AMD module that is then required by a view extending the input/longtext view. To be able to use tinymce API functions within the JS code it's also necessary to make the Extended Tinymce modules a dependency of the galliComments AMD module - though I'm not sure if this specific code is even necessary anymore with tinymce 4.x.

**Comment by propertunist** [comment] 2017-05-03 21:24
i just tested the idea by disabling gallicomments, but tinymce is still crashing in the same way even when gallicomments is disabled.

**Comment by propertunist** [comment] 2017-05-03 21:26
i also just tested tinymce 5.7, but that made no difference.
i did find a stackexchange page where someone described a similar issue and they ran 'tinymce.remove();' before initialising the tinymce instances, but so far i haven't got that to improve the situation.

**Comment by propertunist** [comment] 2017-05-03 21:47
well, the 'remove' idea (with the correct syntax) definitely doesn't fix the issue.

**Comment by propertunist** [comment] 2017-05-03 22:33
one additional point, when i click on an image's thumbnail in the popup, the entire popup content is reloaded via ajax, without the popup being closed. this never results in a JS error. the JS errors only occur when the popup is closed and then reopened.

**Comment by iionly** [comment] 2017-05-17 18:03
I'm closing the issue again as it seems to be fixed by the course of action outlined in https://elgg.org/discussion/view/2646798/thoughts-on-why-tinymce-fails-to-load-when-launched-inside-a-colorbox-lightbox-for-a-2nd-time-on-the-same-page

**Closed as completed by iionly** 2017-05-17 18:03 UTC
